### ISSUE TITLE
Add retry mechanism for bitbucket/slack rest calls

### ISSUE THREAD

**Issue by bulivlad** [bulivlad/pullrequest-watchdog#2]
At the moment we are not using any retry mechanism for any call to bitbucket or slack. For some reason from time to time bitbucket and slack apis are timing-out so we need a way to retry failed calls in order to make sure we are getting all the pull requests/slack users. 
A timeout in bitbucket rest calls cause the PR to be excluded from review list.
A timeout in slack rest calls cause the user to be excluded from team users list.

There is a retry example in  `BitBucketApiRestService.fetchBitbucketUserDetailsByEmail(String)` 

Stacktrace:
```2019-06-04 07:30:12.501 [quartzScheduler_Worker-4] ERROR i.w.p.s.PullRequestRetrieveService - Exception getting PR with id xxxx
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.bitbucket.org/2.0/repositories/slug/repo/pullrequests/xxxx": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:311) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at io.watchdog.pullrequest.service.PullRequestRetrieveService.fetchMemberDetailedPullRequest(PullRequestRetrieveService.java:132) ~[classes!/:?]
	at io.watchdog.pullrequest.service.PullRequestRetrieveService.lambda$getTeamOpenedPullRequests$2(PullRequestRetrieveService.java:68) ~[classes!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_191]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_191]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) [?:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_191]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_191]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_191]
	at io.watchdog.pullrequest.service.PullRequestRetrieveService.getUnapprovedPRs(PullRequestRetrieveService.java:62) [classes!/:?]
	at io.watchdog.pullrequest.service.slack.SlackTeamService.getSlackMessages(SlackTeamService.java:102) [classes!/:?]
	at io.watchdog.pullrequest.quartz.PullRequestRetrieverJob.execute(PullRequestRetrieverJob.java:55) [classes!/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.0.jar!/:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.0.jar!/:?]
Caused by: java.net.SocketTimeoutException: Read timed out

**Comment by bulivlad** [comment]
fixed through https://github.com/bulivlad/pullrequest-watchdog/pull/5
